version: '3.7'
services:

  db:
    image: mdillon/postgis:11
    #    ports:
    #      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: vibing
      POSTGRES_USER: vibing
      POSTGRES_PASSWORD: ghbdtn
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  vibing:
    image: 'vibing'
    depends_on:
      - db
    build: .

  realtime:
    image: 'vibing'
    command: 'python3 /vibing/app/main.py'
    environment:
      CONCURRENCY: 50
      PROXY: http://arkady:arkady13like@rotating_proxy:8080
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  rotating_proxy:
    image: 'vibing'
    restart: always
    command: '/vibing/rotating_proxy'
    depends_on:
      - db
    environment:
      - host=db
      - port=5432
      - user=vibing
      - dbname=vibing
      - password=ghbdtn

  miner:
    image: 'vibing'
    restart: always
    command: '/vibing/miner -mode=miner'
    depends_on:
      - db
    environment:
      - host=db
      - port=5432
      - user=vibing
      - dbname=vibing
      - password=ghbdtn

  assessor:
    image: 'vibing'
    restart: always
    command: '/vibing/miner -mode=assessor'
    depends_on:
      - db
    environment:
      - host=db
      - port=5432
      - user=vibing
      - dbname=vibing
      - password=ghbdtn


volumes:
  database:
